[package]
name = "pdf_parser"
version = "0.1.0"
edition = "2024"

[features]
default = []
napi-support = ["aircraft-types/napi-support"]
wasm-support = ["aircraft-types/wasm-support"]

[dependencies]
pdf = "0.9.1"
fax = "0.2.7"
pdf-extract = "0.8.2"
lopdf = "0.34.0"
md5 = "0.7.0"
aes = "0.8.4"
cbc = "0.1.2"
lazy_static = "1.5.0"
regex = "1.13.1"
aircraft-types = { path = "../types" }
chrono = "0.4.45"