export const properShippingNameMap = {
  UN3480: 'Lithium ion batteries',
  'UN3481-C': 'Lithium ion batteries contained in equipment',
  'UN3481-P': 'Lithium ion batteries packed with equipment',
  UN3090: 'Lithium metal batteries',
  'UN3091-C': 'Lithium metal batteries contained in equipment',
  'UN3091-P': 'Lithium metal batteries packed with equipment',
  UN3171: 'Battery-powered vehicle',
  UN3556: 'Vehicle,lithium ion battery powered',
  UN3557: 'Vehicle,lithium metal battery powered',
  UN3558: 'Vehicle,sodium ion battery powered',
  UN3551: 'Sodium ion batteries',
  'UN3552-P': 'Sodium ion batteries packed with equipment',
  'UN3552-C': 'Sodium ion batteries contained in equipment',
}
