/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')


let nativeBinding = null
let localFileExisted = false
let loadError = null

localFileExisted = existsSync(
  join(__dirname, 'aircraft-rs.win32-x64-msvc.node')
)

try {
  if (localFileExisted) {
    nativeBinding = require('./aircraft-rs.win32-x64-msvc.node')
  } else {
    nativeBinding = require('rust_bindings-win32-x64-msvc')
  }
} catch (e) {
  loadError = e
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { AircraftRs } = nativeBinding

module.exports.AircraftRs = AircraftRs
