/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class AircraftRs {
  constructor()
  getSummaryInfo(path: string): string
  parseGoodsInfo(path: string): string
}
export type FileManagerInstance = FileManager
export declare class FileManager {
  constructor(baseUrl: string, apiKey: string, model: string)
  parsePdf(path: Array<string>): Promise<string>
  parsePdfU8(filename: string, buffer: Array<number>): Promise<string>
  chatWithAiFastAndCheap(fileContents: Array<string>): Promise<string>
  readPdfBuffer(buffer: Array<number>): Promise<string>
}
