export interface EntrustFormData {
  amount: string
  category: string
  checkLocation: string
  destination: string
  id: string
  itemBrand: string
  itemCName: string
  itemColor: string
  itemDanger: string
  itemDangerReason: string
  itemDesc: string
  itemEName: string
  itemFlashPoint: string
  itemMeltingPoint: string
  itemOtherAttachFileDetail: string
  itemSampleHandle: string
  itemSampleHandleOther: string
  itemSendSample: string
  itemSmell: string
  itemSpec: string
  itemStatus: string
  manufacturersCName: string
  manufacturersEName: string
  market: string
  nextYear: string
  paymentCompany: string
  paymentCompanyContact: string
  payType: string
  pieces: string
  principal: string
  principalContact: string
  principalExhort: string
  principalExhortDetail: string
  reportCopy: string
  reportLocation: string
  reportWay: string
  serviceType: string
  systemId: string
  trustee: string
  waybillNo: string
  webWt: string
}
