name: Release Aircraft

on:
  push:
    tags:
      - 'v*'

permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:11}"
          echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.86.0

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: yarn install
        run: |
          corepack enable
          yarn set version stable
          yarn install
      
      - name: Build bindings
        run: |
          cd bindings/node
          yarn
          yarn build
          cd ../../

      - name: Build electron
        run: |
          yarn
          yarn build:electron
      
      - name: Build Tauri-lite 
        run: |
          yarn tauri build
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/bundle/msi/aircraft_${{ env.version }}_x64_zh-CN.msi
            electron/release/${{ env.version }}/aircraft_${{ env.version }}_electron_x64-setup.exe
          name: 'Aircraft ${{ env.version }}'
