name: Release and deploy

on:
  workflow_dispatch:
  push:
    tags:
      - "wxt-v*"

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
        env:
          DISABLE_V8_COMPILE_CACHE: 1
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Query version number
        id: get_version
        shell: bash
        run: |
          VERSION="v$(grep -Po "version\s*:\s*['\"]\K[^'\"]+" packages/wxt/wxt.config.ts)"
          echo "版本: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          sed -i "s/wxt-v[0-9]\+\.[0-9]\+\.[0-9]\+/wxt-$VERSION/g; s/lims-v[0-9]\+\.[0-9]\+\.[0-9]\+/lims-$VERSION/g" packages/wxt/docs/quick_start.md

      - name: Build docs
        run: |
          cd packages/wxt
          yarn docs:build
          cd ../..

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/wxt/docs/.vitepress/dist

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          yarn build:v
          cd packages/wxt
          yarn build
          yarn build:firefox
          cd ../..

      - name: zip chrome extension
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd packages/wxt/.output/chrome-mv3 && zip -q -r ../../../../lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip .
          cd ../../../..
      - name: zip firefox extension
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm i -g web-ext
          web-ext sign --api-key ${{ secrets.FIREFOX_JWT_ISSUER }} --api-secret ${{ secrets.FIREFOX_JWT_SECRET }} --channel unlisted -s packages/wxt/.output/firefox-mv3
          mv web-ext-artifacts/*.xpi lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip
            lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
          name: "WXT ${{ steps.get_version.outputs.VERSION }}"
