name: Release and deploy

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
        env:
          DISABLE_V8_COMPILE_CACHE: 1
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          npm i -g web-ext
      - name: Build
        run: |
          yarn build:v
          cd packages/wxt
          yarn build
          yarn build:firefox
          cd ../..

      - name: Build docs
        run: |
          cd packages/wxt
          yarn docs:build
          cd ../..

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/wxt/docs/.vitepress/dist

      - name: Query version number
        id: get_version
        shell: bash
        run: |
          VERSION="v$(node -p "require('./packages/wxt/.output/chrome-mv3/manifest.json').version")"
          echo "版本: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: zip chrome extension
        run: |
          zip -q -r lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip packages/wxt/.output/chrome-mv3
      - name: zip firefox extension
        run: |
          web-ext sign --api-key ${{ secrets.FIREFOX_JWT_ISSUER }} --api-secret ${{ secrets.FIREFOX_JWT_SECRET }} --channel unlisted -s packages/wxt/.output/firefox-mv3
          mv web-ext-artifacts/*.xpi lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
      
      - name: upload chrome
        uses: actions/upload-artifact@v4
        with:
          name: lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip
          path: lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip

      - name: upload firefox
        uses: actions/upload-artifact@v4
        with:
          name: lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
          path: lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
