name: Release Tauri

on:
  push:
    tags:
      - 'v*'

permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.82.0

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-all-crates: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: npm install
        run: npm install
      
      
      - name: Build Tauri-lite 
        run: |
          npm run tauri build
          New-Item -ItemType Directory -Path .\release
          Move-Item .\src-tauri\target\release\bundle\msi\aircraft_*_x64_zh-CN.msi .\release\aircraft_${{ steps.get_version.outputs.VERSION }}_x64_zh-CN.msi
      
      - name: Download WebView2 Runtime
        run: |
          invoke-webrequest -uri https://github.com/westinyang/WebView2RuntimeArchive/releases/download/109.0.1518.78/Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab -outfile Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab
          Expand .\Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab -F:* ./src-tauri
          Remove-Item .\src-tauri\tauri.conf.json
          Rename-Item .\src-tauri\webview2.x64.json tauri.conf.json
      
      - name: Build Tauri-webview2
        run: |
          npm run tauri build
          Move-Item .\src-tauri\target\release\bundle\msi\aircraft_*_x64_zh-CN.msi .\release\aircraft_${{ steps.get_version.outputs.VERSION }}_fixed_webview2_x64_zh-CN.msi
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/aircraft_${{ steps.get_version.outputs.VERSION }}_x64_zh-CN.msi
            release/aircraft_${{ steps.get_version.outputs.VERSION }}_fixed_webview2_x64_zh-CN.msi
          name: 'Aircraft ${{ steps.get_version.outputs.VERSION }}'
