name: Release Aircraft

on:
  push:
    tags:
      - 'v*'

permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.82.0

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: .
          cache-all-crates: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: npm install
        run: npm install
      
      
      - name: Build Tauri-lite 
        run: |
          npm run tauri build
          New-Item -ItemType Directory -Path .\releases
          Move-Item .\target\release\bundle\msi\aircraft_*_x64_zh-CN.msi .\releases\aircraft_${{ steps.get_version.outputs.VERSION }}_x64_zh-CN.msi
      
      - name: Build bindings
        run: |
          cd bindings/node
          npm install
          npm run build
          cd ../../

      - name: Build electron
        run: |
          npm install
          npm run build:electron
          $V_VERSION = ${{ steps.get_version.outputs.VERSION }}
          $E_VERSION = $V_VERSION.Substring(1)
          Move-Item ./release/$E_VERSION/Aircraft-Windows-$E_VERSION-Setup.exe ./releases/aircraft_${{ steps.get_version.outputs.VERSION }}_electron-setup.exe
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            releases/aircraft_${{ steps.get_version.outputs.VERSION }}_x64_zh-CN.msi
            releases/aircraft_${{ steps.get_version.outputs.VERSION }}_electron-setup.exe
          name: 'Aircraft ${{ steps.get_version.outputs.VERSION }}'
