name: Release Tauri

on:
  push:
    tags:
      - 'v*'

permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            fix-webview2: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            fix-webview2: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.82.0

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-all-crates: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Yarn install
        run: npm install
      
      - name: Download WebView2 Runtime
        if: ${{ matrix.fix-webview2 }}
        run: |
          invoke-webrequest -uri https://github.com/westinyang/WebView2RuntimeArchive/releases/download/109.0.1518.78/Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab -outfile Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab
          Expand .\Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64.cab -F:* ./src-tauri
          Remove-Item .\src-tauri\tauri.conf.json
          Rename-Item .\src-tauri\webview2.x64.json tauri.conf.json

      - name: Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: '${{ steps.get_version.outputs.VERSION }}' # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'Aircraft ${{ steps.get_version.outputs.VERSION }}'
          releaseBody: 'See the assets to download this version and install.'
          args: >
            ${{ matrix.fix-webview2 && 
            '--config src-tauri/tauri.conf.json --filename-pattern "aircraft-webview2-{target}-{arch}"' || 
            '--filename-pattern "aircraft-{target}-{arch}"' }}
